# Generated by Django 6.0.5 on 2026-05-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(default='General', max_length=100)),
                ('read_time', models.CharField(default='5 min', max_length=20)),
                ('excerpt', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blog_posts',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('old_price', models.FloatField(default=0)),
                ('save_percent', models.IntegerField(default=0)),
                ('image', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'bundles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(default='', max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_messages',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('subtitle', models.CharField(default='', max_length=500)),
                ('content', models.TextField(default='')),
            ],
            options={
                'db_table': 'site_pages',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='WhyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='leaf', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'why_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(default='', max_length=500)),
                ('price', models.FloatField(default=0)),
                ('old_price', models.FloatField(default=0)),
                ('weight', models.CharField(default='200g', max_length=50)),
                ('image', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('ingredients', models.TextField(default='')),
                ('usage', models.TextField(default='')),
                ('best_seller', models.BooleanField(default=False)),
                ('new_arrival', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
