# Generated by Django 5.1.6 on 2026-06-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_siterating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grammage_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
